name: publish

# conditions are ORed together, so we need to fail the branch match to only
# trigger on tag changes
on:
  push:
    branches:
      - '!*'
    tags:
      - 'v*'

env:
  CI: true

jobs:
  publish:
    name: 'Publish to NPM'
    runs-on: 'ubuntu-latest'

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda
        with:
          version: latest

      - name: set up node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: install
        run: pnpm install --prefer-offline

      - name: test
        run: pnpm run prepublishOnly

      - name: publish
        uses: JS-DevTools/npm-publish@19c28f1ef146469e409470805ea4279d47c3d35c
        with:
          access: public
          token: ${{ secrets.NPM_TOKEN }}
