name: test

on:
  pull_request:
  push:
    paths-ignore:
      - '**.md'

env:
  CI: true

jobs:
  skip-duplicate-runs:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@f75f66ce1886f00957d99748a42c724f4330bdcf
        with:
          concurrent_skipping: 'same_content'
          paths_ignore: '["**/*.md"]'

  test:
    needs: skip-duplicate-runs
    if: ${{ needs.skip-duplicate-runs.outputs.should_skip != 'true' }}
    name: 'node v${{ matrix.node-version }} on ${{ matrix.os }}'
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        node-version: [20, 22, 24]

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda
        with:
          version: latest

      - name: set up node v${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: install
        run: pnpm install --prefer-offline --frozen-lockfile

      - name: test
        run: pnpm test
